# Generated by Django 5.1.1 on 2024-09-07 21:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms_receiver', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sms',
            name='received_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='sms',
            name='sms_code',
            field=models.CharField(max_length=6),
        ),
    ]
